# Nombre del Worker
name = "workerff"

# Archivo principal de tu Worker
main = "worker.js"  # Cambialo a worker.ts si estás usando TypeScript

# Fecha de compatibilidad de Cloudflare (mantener actualizada)
compatibility_date = "2026-03-04"

# Base de datos D1 vinculada
d1_databases = [
  { 
    binding = "torneos_db",                 # Nombre de la variable que usarás en tu Worker
    database_name = "prod-d1-tutorial",     # Nombre de la base de datos D1
    database_id = "a01f8789-4f1d-4b62-8eae-9f2a84b9d720" # Tu ID de la DB
  }
]

# Opcional: si en algún momento quieres usar variables de entorno
# [[vars]]
# name = "MI_TOKEN"
# value = "1234567890"

# Opcional: si querés usar secretos
# [[secrets]]
# name = "MI_SECRET"
# value = "valor_super_secreto"
