name = "workerff"
main = "worker.js"
compatibility_date = "2026-03-08"

[vars]
PRUEBA = "123"

[d1_databases]
# ejemplo si tu D1 binding se llama MY_DB
binding = "torneos_db"
database_name = "prod-d1-tutorial"
database_id = "a01f8789-4f1d-4b62-8eae-9f2a84b9d720"
