name = "workerff"                 # nombre de tu Worker
type = "javascript"
account_id = "TU_ACCOUNT_ID"      # el que ya pusiste
workers_dev = true

[[d1_databases]]
binding = "MY_DB"                 # nombre que usarás en el código
database_name = "nombre-de-tu-d1"
database_id = "ID_DE_TU_D1"
